const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const service = require('../src/main/workspace/git');
(async () => {
  const cwd = await fs.mkdtemp(path.join(os.tmpdir(), 'hm-git-'));
  await service.mutate(cwd, 'init', {});
  const git = args => execFileSync('git', args, { cwd, windowsHide: true, encoding: 'utf8' });
  git(['config', 'user.name', 'Harness Mix Test']); git(['config', 'user.email', 'test@example.invalid']);
  const file = '中文 空格.txt';
  await fs.writeFile(path.join(cwd, file), 'before\n');
  assert.equal((await service.status(cwd)).files[0].path, file);
  await service.mutate(cwd, 'stage', { path: file });
  assert.match((await service.diff(cwd, file, true)).item.patch.text, /before/);
  await service.mutate(cwd, 'unstage', { path: file });
  assert.equal((await service.status(cwd)).files[0].untracked, true);
  await service.mutate(cwd, 'stage', { path: file });
  await service.mutate(cwd, 'commit', { message: 'fixture initial' });
  await fs.writeFile(path.join(cwd, file), 'after\n');
  assert.match((await service.diff(cwd, file, false)).item.patch.text, /\+after/);
  await service.mutate(cwd, 'stage', { path: file });
  await service.mutate(cwd, 'unstage', { path: file });
  assert.equal(await fs.readFile(path.join(cwd, file), 'utf8'), 'after\n');
  await assert.rejects(service.mutate(cwd, 'stage', { path: '../escape' }), /无效/);
  git(['mv', file, 'rename.txt']);
  const renamed = (await service.status(cwd)).files.find(f => f.from);
  assert.equal(renamed.from, file);
  await service.mutate(cwd, 'unstage', { path: renamed.path });
  assert.equal((await service.status(cwd)).log.length, 1);
  console.log('real Git init, unicode paths, staged/unstaged diff, commit, unborn unstage, rename and traversal checks passed');
})().catch(e => { console.error(e); process.exitCode = 1; });
