const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const { Integrations } = require('../src/main/host/integrations');
const { buildAdapters } = require('../src/main/adapters');
const { NativeProtocol } = require('../src/main/native/protocol');
const { acpServers, namedServers } = require('../src/main/adapters/managed-mcp');

async function main() {
  const root = path.resolve('output/integrations-test', `${Date.now()}`);
  const project = path.join(root, 'project'), home = path.join(root, 'home');
  await fs.mkdir(project, { recursive: true }); await fs.mkdir(home);
  const adapters = new Map(buildAdapters(() => {}).map(a => [a.manifest.id, a]));
  const runtime = { adapters, status: {}, sessions: new Map(), store: { directory: path.join(root, 'data') }, resolveHarnessId: id => id };
  const manager = runtime.integrations = new Integrations(runtime, { home });
  const global = { harnessId: 'claude', scope: 'global' }, local = { harnessId: 'claude', scope: 'project', cwd: project };
  const server = { name: 'probe', command: process.execPath, args: ['probe.cjs'], enabled: true };
  await Promise.all([manager.save({ ...global, server }), manager.save({ ...local, server: { ...server, enabled: false } })]);
  assert.equal((await manager.forSession({ cwd: project }, adapters.get('claude'))).servers.length, 0, 'project disabled entry masks global');
  let snapshot = await manager.list(local);
  assert.equal(snapshot.servers.length, 2); assert.equal(snapshot.servers.filter(s => s.effective).length, 1);
  await manager.remove({ ...local, id: snapshot.servers.find(s => s.scope === 'project').id });
  const selected = await manager.forSession({ cwd: project }, adapters.get('claude'));
  assert.equal(selected.servers[0].name, 'hm-user-probe');
  runtime.sessions.set('s', { adapter: adapters.get('claude'), nativeSessionId: 'native-test', integrationCwd: await fs.realpath(project), integrationServers: selected.records,
    query: { mcpServerStatus: async () => [{ name: 'hm-user-probe', status: 'connected', config: { token: 'DO_NOT_PROJECT' }, tools: [{ name: 'echo' }] }] } });
  snapshot = await manager.list(local);
  assert.equal(snapshot.servers[0].appliedSessions, 1); assert.equal(snapshot.native[0].status, 'connected'); assert.ok(!JSON.stringify(snapshot).includes('DO_NOT_PROJECT'));
  await manager.save({ ...global, server: { ...server, args: ['changed.cjs'] } });
  assert.equal((await manager.list(global)).servers[0].appliedSessions, 0, 'changed config not claimed as applied');
  const reload = new Integrations(runtime, { home }); assert.equal((await reload.list(global)).servers.length, 1);
  await assert.rejects(manager.save({ ...global, server: { ...server, env: { SECRET: 'never' } } }));
  await assert.rejects(manager.save({ ...global, server: { ...server, args: ['--token', 'never'] } }));
  await assert.rejects(manager.save({ ...global, harnessId: 'pi', server }), /no supported/);
  await assert.rejects(manager.remove({ ...local, id: snapshot.servers[0].id }), /scope/);
  await assert.rejects(manager.list({ ...local, cwd: 'relative' }));
  const source = path.join(root, 'source'); await fs.mkdir(path.join(source, 'scripts'), { recursive: true });
  await fs.writeFile(path.join(source, 'SKILL.md'), '---\nname: sample\ndescription: Sample skill\n---\n# Sample\n');
  await fs.writeFile(path.join(source, 'scripts', 'sample.txt'), 'unchanged');
  await manager.skillChange({ ...local, name: 'sample', source, action: 'install' });
  const nativeFile = path.join(project, '.claude/skills/sample/SKILL.md'); assert.match(await fs.readFile(nativeFile, 'utf8'), /Sample/);
  await assert.rejects(manager.skillChange({ ...local, name: 'sample', source, action: 'install' }), /already exists/);
  await manager.skillChange({ ...local, name: 'sample', action: 'disable' });
  await assert.rejects(fs.access(nativeFile)); assert.equal((await manager.list(local)).skills[0].enabled, false);
  await manager.skillChange({ ...local, name: 'sample', action: 'enable' });
  assert.equal(await fs.readFile(path.join(project, '.claude/skills/sample/scripts/sample.txt'), 'utf8'), 'unchanged');
  await assert.rejects(manager.skillChange({ ...local, name: '../escape', source, action: 'install' }));
  await assert.rejects(manager.skillChange({ ...local, name: 'sample', root, action: 'disable' }));
  const link = path.join(project, '.claude/skills/linked');
  await fs.symlink(source, link, process.platform === 'win32' ? 'junction' : 'dir');
  assert.equal((await manager.list(local)).skills.find(s => s.name === 'linked').writable, false);
  await assert.rejects(manager.skillChange({ ...local, name: 'linked', action: 'disable' }), /read-only/);
  const collab = { command: 'native-node', args: ['bridge'], env: { LOCAL_BRIDGE: 'capability' } };
  const acp = acpServers(selected.servers, collab);
  assert.equal(acp.length, 2); assert.equal(acp[1].name, 'harness-mix'); assert.deepEqual(acp[0].env, []);
  assert.ok(namedServers(selected.servers, collab)['hm-user-probe']);
  const catalog = await manager.catalog(); assert.equal(catalog.harnesses.length, 16);
  for (const a of adapters.values()) assert.equal(catalog.harnesses.find(h => h.id === a.manifest.id).mcp, a.manifest.integrations?.mcp === true);
  // Exercise the real protocol dispatcher without starting native processes.
  assert.equal((await NativeProtocol.prototype.request.call({ runtime }, 'codexhost/integrations/catalog', {})).harnesses.length, 16);
  assert.equal((await NativeProtocol.prototype.request.call({ runtime }, 'codexhost/integrations/list', local)).skills.length, 2);
  console.log('integrations: scope precedence, persistence, native status projection, no credential fields, unsupported capabilities, skill install/disable/restore, links, and protocol PASS');
}
main().catch(error => { console.error(error); process.exitCode = 1; });
