const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const os = require('node:os');
const { ReviewStore } = require('../src/main/workspace/review');
const { readText, resolveFile } = require('../src/main/workspace/files');
const { diff } = require('../src/main/workspace/diff');
const { CommandTerminal } = require('../src/main/workspace/terminal');
const { HostRuntime } = require('../src/main/host/runtime');

(async () => {
  const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'hm-workspace-test-'));
  const root = path.join(directory, 'project'); await fs.mkdir(root);
  await fs.writeFile(path.join(root, 'dirty.js'), 'user preexisting change\nold line\n');
  await fs.writeFile(path.join(root, 'deleted.txt'), 'keep original\n');
  await fs.writeFile(path.join(root, '.env'), 'excluded fixture');
  const store = new ReviewStore(directory), id = await store.begin(root);
  await fs.writeFile(path.join(root, 'dirty.js'), 'user preexisting change\nnew line\n');
  await fs.writeFile(path.join(root, 'new.txt'), 'new content\n');
  await fs.unlink(path.join(root, 'deleted.txt'));
  const live = await store.preview(id);
  assert.equal(store.summary(live).live, true);
  assert.equal(live.changes.length, 3);
  assert.ok((await store.load(id)).baseline, 'preview retains persisted baseline');
  assert.equal((await store.detail(id, 'dirty.js')).added, 1);
  await assert.rejects(store.undo(id, 'dirty.js'), /不可撤回/);
  await fs.writeFile(path.join(root, 'new.txt'), 'updated live content\nanother line\n');
  assert.equal((await store.preview(id)).changes.find(c => c.path === 'new.txt').added, 2);
  const review = await store.finish(id);
  assert.equal(review.files.length, 3);
  const reopened = new ReviewStore(directory);
  const detail = await reopened.detail(id, 'dirty.js');
  assert.equal(detail.added, 1); assert.equal(detail.removed, 1);
  assert.equal(detail.rows[0].kind, 'same');
  await fs.writeFile(path.join(root, 'dirty.js'), 'later user change');
  await assert.rejects(reopened.undo(id, 'dirty.js'), /拒绝覆盖/);
  assert.equal(await fs.readFile(path.join(root, 'dirty.js'), 'utf8'), 'later user change');
  await fs.writeFile(path.join(root, 'dirty.js'), 'user preexisting change\nnew line\n');
  await reopened.undo(id, 'dirty.js');
  assert.equal(await fs.readFile(path.join(root, 'dirty.js'), 'utf8'), 'user preexisting change\nold line\n');
  await reopened.undo(id, 'new.txt');
  await assert.rejects(fs.stat(path.join(root, 'new.txt')), { code: 'ENOENT' });
  await reopened.undo(id, 'deleted.txt');
  assert.equal(await fs.readFile(path.join(root, 'deleted.txt'), 'utf8'), 'keep original\n');
  await assert.rejects(reopened.undo(id, 'dirty.js'), /不可撤回/);
  await assert.rejects(readText(root, '.env'), /不参与/);
  await assert.rejects(resolveFile(root, '../escape.txt'), /超出/);
  await fs.mkdir(path.join(directory, 'outside'));
  await fs.symlink(path.join(directory, 'outside'), path.join(root, 'link'), 'junction');
  await assert.rejects(resolveFile(root, 'link/file.txt'), /不跟随/);
  const empty = diff('', ''); assert.equal(empty.rows.length, 0);
  const terminal = new CommandTerminal(() => {});
  const s = terminal.run(root, "Write-Output 'terminal-ok'");
  for (let i = 0; i < 100 && terminal.sessions.get(s.id).running; i++) await new Promise(r => setTimeout(r, 50));
  assert.match(terminal.sessions.get(s.id).output, /terminal-ok/);
  assert.equal(terminal.sessions.get(s.id).exitCode, 0);
  const long = terminal.run(root, 'Start-Sleep -Seconds 30');
  await new Promise(r => setTimeout(r, 300));
  await terminal.stop(long.id);
  for (let i = 0; i < 50 && terminal.sessions.get(long.id).running; i++) await new Promise(r => setTimeout(r, 50));
  assert.equal(terminal.sessions.get(long.id).running, false);
  await terminal.close();
  const rt = new HostRuntime({ dataDirectory: path.join(directory, 'runtime') });
  const updates = [];
  rt.subscribe(e => { if (e.type === 'turn/diff/updated') updates.push(e); });
  await rt.store.load();
  rt.adapters.set('test', {
    manifest: { id: 'test', name: 'Test', capabilities: {} },
    open: async () => ({}), close: async () => {},
    send: async (_session, _text, { emit }) => {
      emit({ kind: 'text-delta', text: 'progress' });
      emit({ kind: 'tool', toolCallId: 'one', title: 'edit', state: 'running' });
      await fs.writeFile(path.join(root, 'dirty.js'), 'native tool edit\n');
      await new Promise(r => setTimeout(r, 2300));
      emit({ kind: 'tool', toolCallId: 'one', title: 'edit', state: 'done' });
      emit({ kind: 'text-delta', text: 'conclusion' });
      emit({ kind: 'completed' });
    },
  });
  rt.status.test = { available: true };
  const t = await rt.createThread({ harnessId: 'test', cwd: root, title: 'runtime fixture' });
  await rt.send(t.id, 'test');
  for (let i = 0; i < 100 && t.status === 'working'; i++) await new Promise(r => setTimeout(r, 25));
  assert.equal(t.status, 'ready');
  const answer = t.messages.at(-1);
  assert.deepEqual(answer.items.map(i => i.kind), ['text', 'tool', 'text']);
  assert.equal(answer.review.files.length, 1);
  assert.equal(answer.review.files[0].path, 'dirty.js');
  assert.ok(updates.some(e => e.turnId === answer.id && e.review?.live && e.review.files.some(f => f.path === 'dirty.js')), 'Runtime pushes live diff without Renderer polling');
  assert.ok(updates.some(e => e.turnId === answer.id && e.review?.live === false), 'Runtime pushes final diff');
  assert.equal(rt.reviewMonitors.size, 0);
  assert.ok(answer.endedAt >= answer.at);
  await rt.undoFile(t.id, answer.id, 'dirty.js');
  assert.match(await fs.readFile(path.join(root, 'dirty.js'), 'utf8'), /user preexisting change/);
  await rt.close();
  console.log('baseline preserves dirty edits; add/delete/modify undo; conflict, traversal, junction guards; persisted review; real pwsh output/stop passed');
})().catch(e => { console.error(e); process.exit(1); });
